spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DBURL}/${DB}
    username: ${DBUSER}
    password: ${DBPASSWORD}
#
#    url: jdbc:mysql://127.0.0.1:3306/ljj
#    username: root
#    password: qwer1234

#    url: jdbc:mysql://db-master-stateful-0.db-stateful-headless:3306/test_db
#    username: master
#    password: qwer1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl:  true
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret: mysecret.20231011_.qwer1234.Dkagh1234! # 길어야 함
  token.expired-time-ms: 2592000000 # 30 days