spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${DBURL}/${DB}
#    username: ${DBUSER}
#    password: ${DBPASSWORD}
#
#    url: jdbc:mysql://127.0.0.1:3306/ljj
#    username: root
#    password: qwer1234

#    url: jdbc:mysql://db-master-stateful-0.db-stateful-headless:3306/test_db
#    username: root
#    password: root

    url: jdbc:mysql://mydb.cjgeoyu2bayw.eu-north-1.rds.amazonaws.com:3306/resource_project
    username: admin
    password: qwer1234

#  DBURL = "jdbc:mysql://mydb.cjgeoyu2bayw.eu-north-1.rds.amazonaws.com:3306"
#  DB = "resource_project"
#  DBUSER = "admin"
#  DBPASSWORD = "qwer1234"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl:  true
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret: mysecret.20231011_.qwer1234.Dkagh1234! # 길어야 함
  token.expired-time-ms: 2592000000 # 30 days

